[build-system]
requires = [
    "setuptools==80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.LAWVNameChange"
version = "1.0.12"
description = "A docassemble extension."
readme = "README.md"
authors = [
    { name = "Dane W. Henry, Esq.", email = "dhenry@lawv.net" },
]
dependencies = []
license = "MIT"
license-files = [
    "LICENSE",
]

[project.urls]
Homepage = "https://docassemble.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
